package com.rdupuis.amikcal.relations;

public enum REL_TYP_CD {
	UA_COMP,CFOOD,  CMOVE,  CWEIGHT,NRJ_REF_INTRNL,
	COMPONENT, NRJ_REF_EQUIV, CSTM_NRJ_REF, UNIT_EQUIV, UNIT_INTER_LINK,
	COMP_EQUIV, QTY, QTY_EQUIV, UNDEFINED;

}
